name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install gnome-keyring curl
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry config --local virtualenvs.create false
          poetry install
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pytest