[global]
suppressDeprecationWarnings = true

[client]
# hide error details like warnings about deprecated functions
showErrorDetails = false
disableWidgetStateDuplicationWarning = true

[ui]
hideTopBar = true
