[global]
suppressDeprecationWarnings = true

[client]
# hide error details like warnings about deprecated functions
showErrorDetails = true
disableWidgetStateDuplicationWarning = true

[ui]
hideTopBar = true
